name: CD

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Cache SBT dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/**') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Check code formatting
        run: sbt scalafmtSbtCheck scalafmtCheckAll

      - name: Check compilation
        run: sbt compile

      - name: Run tests
        run: sbt test

      - name: Build application JAR
        run: sbt package

    # Future deployment steps can be added here
    # - name: Deploy to production
    #   run: echo "Deployment steps would go here"
